// angular-todo-test/src/app/app.component.ts
import { Component } from '@angular/core';
import type Todo from './todo.model';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-root',
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'Angular To-Do App';
  todos: Todo[] = [];
  text: string = '';

  addTodo() {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();

    if (!this.text.trim()) return;
    this.todos.push({
      id: Date.now(),
      text: this.text,
      completed: false,
    });
    this.text = '';

    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `ANGULAR -> A adição de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
  }

  toggleTodo(id: number) {
    const todo = this.todos.find((t) => t.id === id);
    if (todo) {
      todo.completed = !todo.completed;
    }
  }

  deleteTodo(id: number) {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();
    this.todos = this.todos.filter((t) => t.id !== id);
    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `ANGULAR -> A remoção de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
  }
}

<h1>TO-DO List em ANGULAR 🅰️</h1>

<form (ngSubmit)="addTodo()" class="form">
  <input
    required
    type="text"
    class="input"
    [(ngModel)]="text"
    name="todoText"
    placeholder="Digite uma tarefa" />
  <span class="input-border"></span>
  <button type="submit">Adicionar</button>

</form>

<ul>
  <li *ngFor="let todo of todos">
    <input
      type="checkbox"
      [checked]="todo.completed"
      (change)="toggleTodo(todo.id)"
    />
    <span [ngStyle]="{ 'text-decoration': todo.completed ? 'line-through' : 'none' }">
      {{ todo.text }}
    </span>
    <button (click)="deleteTodo(todo.id)">🗑️</button>
  </li>
</ul>

// vue-todo-test/src/App.vue
<template>
    <div class="container">
        <h1>TO-DO List em VUE ✅</h1>

        <form @submit.prevent="addTodo" class="form">
            <input
                v-model="text"
                type="text"
                class="input"
                placeholder="Digite uma tarefa"
                required />
                <span class="input-border" />
            <button type="submit">Adicionar</button>
        </form>

        <div class="todos">
            <TodoItem
                v-for="todo in todos"
                :key="todo.id"
                :todo="todo"
                @toggle="toggleTodo"
                @delete="deleteTodo"
            />
        </div>
    </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import TodoItem from './components/TodoItem.vue'
import type Todo from './types/Todo'

const text = ref('')
const todos = ref<Todo[]>([])

function addTodo() {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();

    if (!text.value.trim()) return
    todos.value.push({ id: Date.now(), text: text.value, completed: false })
    text.value = ''

    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(`VUE -> A adição de uma nova tarefa levou ${t1 - t0} milissegundos`);
}

function toggleTodo(id: number) {
    const todo = todos.value.find((t: Todo) => t.id === id)
    if (todo) todo.completed = !todo.completed
}

function deleteTodo(id: number) {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();
    todos.value = todos.value.filter((t: Todo) => t.id !== id)
    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `VUE -> A remoção de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
}
</script>
