// react-todo-test/src/App.tsx
import { useState } from "react";
import TodoItem from "./components/TodoItem";
import type Todo from "./types/Todo";

function App() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [text, setText] = useState("");

  const addTodo = () => {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();

    if (text.trim() === "") return;
    const newTodo: Todo = {
      id: Date.now(),
      text,
      completed: false,
    };
    setTodos([...todos, newTodo]);
    setText("");

    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `REACT -> A adição de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
  };

  const toggleTodo = (id: number) => {
    setTodos(
      todos.map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo
      )
    );
  };

  const deleteTodo = (id: number) => {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();
    setTodos(todos.filter((todo) => todo.id !== id));
    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `REACT -> A remoção de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
  };

  return (
    <div style={{ padding: "2rem" }}>
      <h1>TO-DO List em REACT 🌐</h1>

      <form
        className="form"
        onSubmit={(e) => {
          e.preventDefault();
          addTodo();
        }}
      >
        <input
          required
          type="text"
          className="input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Digite uma tarefa"
        />
        <span className="input-border" />

        <button type="submit">Adicionar</button>
      </form>

      <div style={{ marginTop: "1rem" }}>
        {todos.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            toggleTodo={toggleTodo}
            deleteTodo={deleteTodo}
          />
        ))}
      </div>
    </div>
  );
}

export default App;

// vue-todo-test/src/App.vue
<template>
    <div class="container">
        <h1>TO-DO List em VUE ✅</h1>

        <form @submit.prevent="addTodo" class="form">
            <input
                v-model="text"
                type="text"
                class="input"
                placeholder="Digite uma tarefa"
                required />
                <span class="input-border" />
            <button type="submit">Adicionar</button>
        </form>

        <div class="todos">
            <TodoItem
                v-for="todo in todos"
                :key="todo.id"
                :todo="todo"
                @toggle="toggleTodo"
                @delete="deleteTodo"
            />
        </div>
    </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import TodoItem from './components/TodoItem.vue'
import type Todo from './types/Todo'

const text = ref('')
const todos = ref<Todo[]>([])

function addTodo() {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();

    if (!text.value.trim()) return
    todos.value.push({ id: Date.now(), text: text.value, completed: false })
    text.value = ''

    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(`VUE -> A adição de uma nova tarefa levou ${t1 - t0} milissegundos`);
}

function toggleTodo(id: number) {
    const todo = todos.value.find((t: Todo) => t.id === id)
    if (todo) todo.completed = !todo.completed
}

function deleteTodo(id: number) {
    /*
     * NOTE: A medição de desempenho é feita aqui, mas não é usada para nada.
     * Isso é apenas para simular um atraso na medição de desempenho
     * e para que o teste de desempenho funcione corretamente.
     */
    const t0 = performance.now();
    todos.value = todos.value.filter((t: Todo) => t.id !== id)
    // NOTE: Essas linhas abaixo (até o fim do escopo dessa função) é apenas para simular um atraso na medição de desempenho
    const t1 = performance.now();
    console.log(
      `VUE -> A remoção de uma nova tarefa levou ${t1 - t0} milissegundos`
    );
}
</script>
